# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-tangorpro.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/tangorpro


include vendor/pixeloverlays/tangorpro/overlays.mk
