# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-felix.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/felix


include vendor/pixeloverlays/felix/overlays.mk
