PRODUCT_PACKAGES += \
    ClearCallingSettingsOverlay2022 \
    CompanionDeviceManagerOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleFuturePantherOverlay \
    SettingsGooglePantherOverlay \
    SettingsGooglePantherOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    SettingsGooglePantherOverlayVendorRRO \
