PRODUCT_PACKAGES += \
    ClearCallingSettingsOverlay2022 \
    CompanionDeviceManagerOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleCheetahOverlay \
    SettingsGoogleFutureCheetahOverlay \
    SettingsGoogleCheetahOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    SettingsGoogleCheetahOverlayVendorRRO \
