PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PixelDisplayService__shiba__auto_generated_rro_product \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleShibaOverlay \
    SettingsGoogleShibaOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    SettingsGoogleShibaOverlayVendorRRO \
