PRODUCT_PACKAGES += \
    AvatarPickerPixelOverlay \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    PixelDisplayService__shiba__auto_generated_rro_product \
    PixelNfcOverlayCommon \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleShibaOverlay \
    SettingsGoogleShibaOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGoogleShibaOverlayVendorRRO \
