PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PixelDisplayService__husky__auto_generated_rro_product \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleHuskyOverlay \
    SettingsGoogleHuskyOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    SettingsGoogleHuskyOverlayVendorRRO \
